version: '2'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./server.crt:/etc/nginx/ssl/server.crt
      - ./server.key:/etc/nginx/ssl/server.key
      - ./.htpasswd:/etc/nginx/.htpasswd
    ports:
      - "443:443"